import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { Brain, TrendingUp, TrendingDown, Minus } from 'lucide-react'

// Fallback sentiment data when Gemini is not yet run
const FALLBACK_SENTIMENT = {
  generated_at: '2026-04-08T00:00:00Z',
  source: 'embedded-fallback',
  overall_sentiment: 'cautiously_optimistic',
  overall_score: 62,
  summary: 'Malaysia\'s WFH fuel-crisis policy is showing early positive signals in mobility reduction, but long-term effectiveness depends on private sector participation and structural PT investment.',
  signals: [
    { dimension: 'Fuel savings impact', score: 71, direction: 'positive', analysis: 'Public sector WFH is delivering ~2.9M litres/week savings — meaningful but equivalent to only 34% of MCO peak savings. Requires private sector extension to be transformative.' },
    { dimension: 'PT ridership pressure', score: 55, direction: 'neutral', analysis: 'Ridership will decline 8–12% as commuter trips fall. This is good for subsidy relief but may hurt Prasarana revenue and create a policy tension with PT investment goals.' },
    { dimension: 'Economic risk', score: 68, direction: 'positive', analysis: 'Unlike MCO, economic activity in retail, logistics, and manufacturing continues uninterrupted. Private professional services WFH at ~40% shows minimal output impact based on 2020–2022 precedent.' },
    { dimension: 'Policy equity', score: 41, direction: 'negative', analysis: 'WFH mandate disproportionately benefits urban, office-based workers. Blue-collar, logistics, and field workers — who travel furthest and spend most on fuel — receive no relief from this policy.' },
    { dimension: 'Long-term modal shift', score: 58, direction: 'neutral', analysis: 'WFH may paradoxically reduce PT habit formation. Workers who stop commuting by train may switch to car when WFH ends. Active investment in PT quality during this period is critical.' },
  ],
  recommendation: 'Extend WFH to private professional sector with tax incentives to double fuel savings. Pair with MRT3 construction acceleration and RON95 graduated pricing to address equity gap. Target: MF-Index below 50 within 60 days.',
  model: 'gemini-1.5-pro',
}

// FIX: Added 'unknown' fallback to prevent crash if data direction is missing or misspelled
const DIRECTION_ICONS = {
  positive: { icon: TrendingUp,   color: '#3B6D11', bg: '#EAF3DE' },
  neutral:  { icon: Minus,        color: '#BA7517', bg: '#FAEEDA' },
  negative: { icon: TrendingDown, color: '#A32D2D', bg: '#FCEBEB' },
  unknown:  { icon: Minus,        color: '#9CA3AF', bg: '#F3F4F6' } 
}

function ScoreBar({ score, color }) {
  return (
    <div className="h-1.5 bg-gray-100 rounded-full overflow-hidden mt-2">
      <motion.div
        initial={{ width: 0 }}
        animate={{ width: `${score}%` }}
        transition={{ duration: 0.8, ease: 'easeOut' }}
        className="h-full rounded-full"
        style={{ background: color }}
      />
    </div>
  )
}

export default function SentimentPanel({ pipelineData }) {
  const [sentiment, setSentiment] = useState(null)
  const [loading, setLoading] = useState(true)
  const [expanded, setExpanded] = useState(null)

  useEffect(() => {
    if (pipelineData) {
      setSentiment(pipelineData)
      setLoading(false)
      return
    }

    fetch('/data/sentiment.json')
      .then(r => r.ok ? r.json() : Promise.reject())
      .then(d => { setSentiment(d); setLoading(false) })
      .catch(() => { 
        setSentiment(FALLBACK_SENTIMENT); 
        setLoading(false);
      })
  }, [pipelineData])

  if (loading) return (
    <div className="max-w-6xl mx-auto px-4 py-16">
      <div className="glass rounded-3xl p-8 flex items-center justify-center h-48">
        <div className="flex items-center gap-2 text-gray-400">
          <div className="w-4 h-4 border-2 border-blue-200 border-t-blue-500 rounded-full animate-spin" />
          Loading AI insights...
        </div>
      </div>
    </div>
  )

  // FIX: Final safety gate. If data is still missing, don't map it.
  if (!sentiment || !sentiment.signals) return null;

  const d = sentiment
  const overallColor = d.overall_score >= 70 ? '#3B6D11' : d.overall_score >= 50 ? '#BA7517' : '#A32D2D'

  return (
    <section className="max-w-6xl mx-auto px-4 py-16">
      <div className="text-center mb-10">
        <div className="text-xs font-medium text-gray-400 uppercase tracking-widest mb-3">AI-powered insight</div>
        <h2 className="text-3xl font-light text-gray-800">Gemini policy sentiment analysis</h2>
        <p className="text-sm text-gray-500 mt-3 max-w-lg mx-auto">
          Daily analysis generated by Google Gemini 1.5 Pro from consolidated mobility, fuel, ridership, and WFH data
        </p>
      </div>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
        className="glass rounded-3xl p-8 mb-6">
        <div className="flex items-start justify-between flex-wrap gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center">
              <Brain size={20} color="#185FA5" />
            </div>
            <div>
              <div className="text-xs text-gray-400 font-medium">Overall policy sentiment</div>
              <div className="text-sm font-semibold text-gray-700 capitalize mt-0.5">
                {d.overall_sentiment?.replace(/_/g, ' ') || 'Calculating...'}
              </div>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <div className="text-4xl font-light" style={{ color: overallColor }}>{d.overall_score}</div>
            <div className="text-xs text-gray-400">/100</div>
          </div>
        </div>

        <ScoreBar score={d.overall_score} color={overallColor} />
        <p className="text-sm text-gray-600 leading-relaxed mt-5 mb-5 border-l-2 border-blue-200 pl-4">{d.summary}</p>

        <div className="flex items-center gap-2 text-xs text-gray-400">
          <span className="px-2 py-1 rounded-full bg-blue-50 text-blue-600 font-medium">{d.model}</span>
          {d.source === 'embedded-fallback'
            ? <span className="px-2 py-1 rounded-full bg-amber-50 text-amber-600">embedded fallback · run pipeline for live analysis</span>
            : <span className="px-2 py-1 rounded-full bg-green-50 text-green-600">generated {new Date(d.generated_at).toLocaleDateString('en-MY')}</span>
          }
        </div>
      </motion.div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
      {d.signals.map((s, i) => {
        const dir = DIRECTION_ICONS[s.direction?.toLowerCase()] || DIRECTION_ICONS.unknown;
        const Icon = dir.icon;
      
        return (
          <motion.div key={s.dimension}
            initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.07 }}
            className="glass rounded-2xl p-5 cursor-pointer hover:shadow-md transition-all"
            onClick={() => setExpanded(expanded === i ? null : i)}>
            <div className="flex items-center justify-between mb-2">
              <div className="text-sm font-medium text-gray-700">{s.dimension}</div>
              <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                style={{ background: dir.bg }}>
                <Icon size={13} color={dir.color} />
              </div>
            </div>
            <div className="text-2xl font-light mb-1" style={{ color: dir.color }}>{s.score}</div>
            <ScoreBar score={s.score} color={dir.color} />
      
            <div
              style={{
                maxHeight: expanded === i ? '200px' : '0px',
                overflow: 'hidden',
                transition: 'max-height 0.35s ease',
              }}
            >
              <p className="text-xs text-gray-500 leading-relaxed mt-3">
                {s.analysis}
              </p>
            </div>
      
            <div className="text-xs text-gray-300 mt-2">
              {expanded === i ? '▲ collapse' : '▼ expand analysis'}
            </div>
          </motion.div>
        )
      })}
      </div>

      <div className="glass rounded-3xl p-6 border border-blue-100">
        <div className="text-xs font-medium text-blue-600 uppercase tracking-widest mb-3">Gemini recommendation</div>
        <p className="text-sm text-gray-700 leading-relaxed">{d.recommendation}</p>
      </div>
    </section>
  )
}
